### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by WhXl** [cong/yolov5_deepsort_tensorrt_cpp#1]
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    import yolo_deepsort
ModuleNotFoundError: No module named 'yolo_deepsort'

**Comment by cong** [comment]
> Traceback (most recent call last): File "demo.py", line 11, in import yolo_deepsort ModuleNotFoundError: No module named 'yolo_deepsort'

能具体说明下报错的情景么？
Can you specify the situation where the error is reported?

**Comment by lanzhou2012** [comment]
I got the same error, too. 
ModuleNotFoundError: No module named 'yolo_deepsort'.

**Comment by Luna2199** [comment]
请问 `yolo_deepsort.cpython-37m-x86_64-linux-gnu.so`文件是如何生成的，可以提供源码或方法吗？产生`ModuleNotFoundError: No module named 'yolo_deepsort' `错误，可能是共享的so文件与当前使用的系统不适配。

**Comment by cong** [comment]
> 请问 `yolo_deepsort.cpython-37m-x86_64-linux-gnu.so`文件是如何生成的，可以提供源码或方法吗？产生`ModuleNotFoundError: No module named 'yolo_deepsort' `错误，可能是共享的so文件与当前使用的系统不适配。

您好，暂时没办法提供源码，

**Comment by hygxy** [comment]
same error on jetson agx xavier
