### ISSUE TITLE
requirements.txt not found

### ISSUE THREAD

**Issue by YuzhouPeng** [cong/yolov5_deepsort_tensorrt_cpp#2]
could you please tell me where is requirements.txt？

meanwhile, I pip install yolov5_deepsort_tensorrt project's requirements.txt, then I run demo.py I found this error:

Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    import yolo_deepsort
ImportError: libyolov5.so: cannot open shared object file: No such file or directory

**Comment by cong** [comment]
There is no requirements.txt, I made a typo in the README.

Can you tell the situation how you run the demo.py?

**Comment by YuzhouPeng** [comment]
I run demo.py and output following errors:

Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    import yolo_deepsort
ModuleNotFoundError: No module named 'yolo_deepsort'

**Comment by cong** [comment]
> 

What platform did you test on ？x86 or Jetson NX/TX2 ?

**Comment by YuzhouPeng** [comment]
x86

**Comment by cong** [comment]
> x86

Ubuntu with python 3.7 ?

**Comment by YuzhouPeng** [comment]
yes, ubuntu with python 3.7

**Comment by cong** [comment]
> yes, ubuntu with python 3.7

I haven’t encountered this kind of problem for the time being, I can't help you now, sorry for that.
